# Generated by Django 5.2.15 on 2026-06-16 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_prompt', models.TextField()),
                ('format_type', models.CharField(choices=[('Real-Video', 'Real-Video'), ('Anime-Video', 'Anime-Video'), ('Carousel', 'Carousel')], max_length=20)),
                ('script_data', models.JSONField(blank=True, default=dict)),
                ('json_timeline', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('render_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('Audio', 'Audio'), ('Image', 'Image'), ('Video_Final', 'Video_Final')], max_length=20)),
                ('file_url', models.CharField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='engine.project')),
            ],
        ),
    ]
