# Generated by Django 5.2.15 on 2026-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Image', 'Image'), ('Video_Clip', 'Video_Clip'), ('Video_Final', 'Video_Final')], max_length=20),
        ),
    ]
